In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('KAG_energydata_complete.csv')

In [4]:
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [5]:
df.isnull().sum().sum()

np.int64(0)

In [7]:
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='str')

In [9]:
df['date']=pd.to_datetime(df['date'])

In [11]:
df['days']=df['date'].dt.day

In [12]:
df['hour']=df['date'].dt.hour

In [22]:
df['dow']=df['date'].dt.day_of_week

In [23]:
df['is_weekend']=np.where(df['dow'].isin(['Sunday','Saturday']),1,0)

In [24]:
df.drop('dow',axis=1,inplace=True)

In [25]:
df['is_weekend']

0        0
1        0
2        0
3        0
4        0
        ..
19730    0
19731    0
19732    0
19733    0
19734    0
Name: is_weekend, Length: 19735, dtype: int64

In [29]:
df.drop('date',axis=1,inplace=True)

In [30]:
##Outliers detection
print("highest allowed value of appliance",df['Appliances'].mean() + 3 * df['Appliances'].std())
print("lowest allowed value of appliance",df['Appliances'].mean() - 3 * df['Appliances'].std())

highest allowed value of appliance 405.269629808317
lowest allowed value of appliance -209.8797134161204

In [34]:
(df['Appliances'] < 0).sum()

np.int64(0)

In [ ]:
(df['Appliances'] > 1000).sum()

np.int64(2)

In [36]:
df.count()

Appliances     19735
lights         19735
T1             19735
RH_1           19735
T2             19735
RH_2           19735
T3             19735
RH_3           19735
T4             19735
RH_4           19735
T5             19735
RH_5           19735
T6             19735
RH_6           19735
T7             19735
RH_7           19735
T8             19735
RH_8           19735
T9             19735
RH_9           19735
T_out          19735
Press_mm_hg    19735
RH_out         19735
Windspeed      19735
Visibility     19735
Tdewpoint      19735
rv1            19735
rv2            19735
days           19735
hour           19735
is_weekend     19735
dtype: int64

In [43]:
df[(df['Appliances']>405.26)|(df['Appliances']<-209.87)]

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2,days,hour,is_weekend
11,580,60,20.066667,46.396667,19.426667,44.400000,19.790000,44.826667,19.000000,46.430000,...,734.433333,91.166667,5.833333,40.000000,4.616667,8.827838,8.827838,11,18,0
12,430,50,20.133333,48.000000,19.566667,44.400000,19.890000,44.900000,19.000000,46.363333,...,734.500000,91.000000,6.000000,40.000000,4.600000,34.351142,34.351142,11,19,0
103,500,0,19.700000,45.590000,18.890000,44.230000,19.890000,44.900000,19.166667,45.026667,...,742.883333,90.166667,5.000000,30.833333,3.950000,49.634203,49.634203,12,10,0
104,450,0,19.730000,47.793333,18.926667,44.230000,19.890000,44.900000,19.360000,45.360000,...,742.966667,89.333333,5.000000,32.666667,4.000000,31.674663,31.674663,12,10,0
308,420,20,19.500000,41.326667,19.000000,40.500000,19.200000,42.290000,18.760000,41.266667,...,756.900000,88.333333,5.000000,32.666667,1.400000,3.422332,3.422332,13,20,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19684,580,0,23.633333,47.226667,24.814000,43.472000,26.166667,40.500000,24.500000,43.500000,...,756.166667,79.333333,1.666667,61.000000,12.266667,27.740214,27.740214,27,9,0
19685,660,0,23.760000,47.693333,25.497143,42.595714,26.033333,40.693333,24.500000,43.560000,...,756.183333,78.666667,1.333333,61.000000,12.333333,4.105907,4.105907,27,9,0
19695,620,0,24.356667,48.326667,26.777143,39.567143,27.533333,41.963333,24.463333,44.363333,...,756.150000,69.000000,1.500000,64.000000,13.250000,11.703932,11.703932,27,11,0
19733,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,...,755.200000,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784,27,17,0
19734,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,...,755.200000,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851,27,18,0